### PR TITLE
Remove universal support + Update to 3.6.8 and 3.7.2 + fixes - 3.3 and 3.4

### PR DESCRIPTION
**Pull request by sashkab**
Changes:

1. Remove universal support
1. Drop python 3.3 and python 3.4.
1. Update python 3.6 to 3.6.8 and 3.7 to 3.7.2
1. Latest versions of pip, setup tools and wheel where supported (2.7, 3.4+)
1. Don't build/install docs on 3.6+
1. Update readme — explain deprecation is only for universal part.
1. Fix build on Mojave for python27, python35 and python36.

### CODE REVIEW

**Comment by sashkab** [comment]
@BrendanSimon, @desertkun — could you please give this pull request a spin before I merge into master? This removes universal support, but otherwise build latest versions of Python.

**Comment by desertkun** [comment]
Checked all of versions by running `brew install https://raw.githubusercontent.com/sashkab/homebrew-python/29-not-universal/Formula/pythonNN.rb` works fine. 

Also, this PR would be a nice opportunity to bring #27 back to life.

**Comment by sashkab** [comment]
@desertkun  thanks. Regarding bottles — I'll reopen issue, but my time is somewhat limited — not sure I will able to get this done today. Maybe next time I will need to switch to a different project for awhile :)

**Comment by sashkab** [comment]
Btw, @desertkun which version of macOS did you use: Mojave or different?

**Comment by sashkab** [comment]
CI failing with python 2.7, 3.5, 3.6 and 3.7. Will need to investigate further. 

Looks like 3.x is style related, while 2.7 is test related.

**Comment by desertkun** [comment]
On a side note, these installations have a warning `pythonNN is keg-only, which means it was not symlinked into /usr/local` that means that I cannot run it without calling it from `/usr/local/opt/pythonNN/bin/pythonNN` (which is fine for my use case as I need to just make a `virtualenv` from it `/usr/local/opt/pythonNN/bin/pythonNN -m virtualenv test`)

**Comment by sashkab** [comment]
> have a warning `pythonNN is keg-only, which means it was not symlinked into /usr/local`

This is by design, so it does not conflicts with python@2 and python.

**Comment by sashkab** [comment]
Ran into zlib support issue on Mojave, opened upstream bug -- Homebrew/homebrew-core#34511.

**Comment by sashkab** [comment]
Oh.. zlib is broken in 3.3-3.6. 

Don't have time now will deal with this later. 

Ping me if no updates in a week :)

**Comment by sashkab** [comment]
Still extremely busy, sorry...

**Comment by desertkun** [comment]
Take your time 👍

**Comment by sashkab** [comment]
Ok, it builds now fine, but travis CI fails on `brew doctor` stage. wtf?

**Comment by desertkun** [comment]
Congrats! The next logical step would be #27

**Pull request merged**
